changelog:
  categories:
    - title: Breaking changes
      labels: [breaking-change]
    - title: Enhancements
      labels: [enhancement, feature]
    - title: Bug fixes
      labels: [bug]
    - title: Documentation
      labels: [documentation]
    - title: Other changes
      labels: ["*"]
  exclude:
    labels: [skip-changelog]
    authors: [dependabot]
